#!groovy
properties([disableConcurrentBuilds()])

pipeline {
    agent {
        label 'master'
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    stages {
        stage('First step') {
            steps {
                sh 'ssh ssh dm_okhrimenko@34.91.243.196'
            }
        }
    }
}
